use anchor_lang::prelude::*;
use anchor_spl::{
    associated_token::AssociatedToken,
    token::{Mint, Token, TokenAccount},
    token_interface,
};

use crate::{
    raydium_cp_swap,
    state::{BondingCurve, Global},
    CurveLaunchpadError,
};

/// Emitted on successful Raydium CPMM migration. Defined inline because
/// `events.rs` is owned by a separate workstream.
#[event]
pub struct MigrateEvent {
    pub mint: Pubkey,
    pub bonding_curve: Pubkey,
    pub pool_state: Pubkey,
    pub lp_mint: Pubkey,
    pub quote_deposited: u64,
    pub meme_deposited: u64,
    pub lp_received: u64,
    pub timestamp: i64,
}

#[derive(Accounts)]
pub struct Migrate<'info> {
    /// Pays the Raydium pool-state rent (~1.1 SOL) and ATA rent for the
    /// program-owned LP token account. Does NOT fund the pool reserves —
    /// those come from the bonding curve's own LST/MEME balances.
    #[account(mut)]
    pub creator: Signer<'info>,

    #[account(
        seeds = [Global::SEED_PREFIX],
        bump,
    )]
    pub global: Box<Account<'info, Global>>,

    /// MEME mint (Token v1). The curve's own token.
    pub mint: Box<Account<'info, Mint>>,

    /// LST quote mint (Token-2022 with TransferFee). Must match `global.quote_mint`.
    /// Mint-ordering is handled at the CPI call site — the program picks
    /// token_0/token_1 based on raw key comparison, so the caller does not
    /// need to engineer mint vanity prefixes.
    #[account(
        address = global.quote_mint @ CurveLaunchpadError::InvalidQuoteMint,
    )]
    pub quote_mint: Box<InterfaceAccount<'info, token_interface::Mint>>,

    /// The bonding curve PDA. Acts as authority for both the LST and MEME
    /// source ATAs as well as the retained LP token account.
    #[account(
        mut,
        seeds = [BondingCurve::SEED_PREFIX, mint.to_account_info().key.as_ref()],
        bump,
    )]
    pub bonding_curve: Box<Account<'info, BondingCurve>>,

    /// Bonding curve's LST ATA. Routed into the token_0_X or token_1_X slot
    /// based on which mint is lexicographically smaller.
    #[account(
        mut,
        associated_token::mint = quote_mint,
        associated_token::authority = bonding_curve,
        associated_token::token_program = token_program_2022,
    )]
    pub bonding_curve_quote_account: Box<InterfaceAccount<'info, token_interface::TokenAccount>>,

    /// Bonding curve's MEME ATA. Routed into the opposite slot.
    #[account(
        mut,
        associated_token::mint = mint,
        associated_token::authority = bonding_curve,
    )]
    pub bonding_curve_token_account: Box<Account<'info, TokenAccount>>,

    /// CHECK: Which config the pool belongs to. Validated by Raydium CPMM.
    pub amm_config: UncheckedAccount<'info>,

    /// CHECK: Pool vault & lp mint authority PDA. Validated by Raydium CPMM.
    pub authority: UncheckedAccount<'info>,

    /// CHECK: Pool state account, init by cp-swap.
    #[account(mut)]
    pub pool_state: UncheckedAccount<'info>,

    /// CHECK: LP mint, init by cp-swap.
    #[account(mut)]
    pub lp_mint: UncheckedAccount<'info>,

    /// LP token account owned by the bonding_curve PDA. Created lazily by the
    /// associated token program. We retain LP custody (no burn) so the
    /// program can later CPI `withdraw` on Raydium for the flip post-mig
    /// LP-drain path (see SPEC.md §4).
    #[account(
        init_if_needed,
        payer = creator,
        associated_token::mint = lp_mint,
        associated_token::authority = bonding_curve,
    )]
    pub program_lp_token: Box<Account<'info, TokenAccount>>,

    /// CHECK: token_0 vault for the pool, init by cp-swap. The caller is
    /// responsible for deriving this against the same token_0_mint the
    /// program will pick at runtime (i.e. min(meme, lst) by raw key bytes).
    #[account(mut)]
    pub token_0_vault: UncheckedAccount<'info>,

    /// CHECK: token_1 vault for the pool, init by cp-swap. Same caveat —
    /// derive against max(meme, lst).
    #[account(mut)]
    pub token_1_vault: UncheckedAccount<'info>,

    /// CHECK: Raydium create-pool fee receiver. Validated by Raydium CPMM.
    #[account(mut)]
    pub create_pool_fee: UncheckedAccount<'info>,

    /// CHECK: Oracle observations account, init by cp-swap.
    #[account(mut)]
    pub observation_state: UncheckedAccount<'info>,

    /// Typed Raydium CPMM program handle, generated by `declare_program!`
    /// at the crate root from the on-chain IDL.
    pub cp_swap_program: Program<'info, raydium_cp_swap::program::RaydiumCpSwap>,

    /// Legacy SPL Token program — the create-pool fee account in the IDL's
    /// `token_program` slot uses legacy Token, plus this is the MEME side.
    pub token_program: Program<'info, Token>,

    /// CHECK: Token-2022 program — used for the LST side. Address-checked
    /// against the canonical Token-2022 program id.
    #[account(address = anchor_spl::token_2022::ID)]
    pub token_program_2022: UncheckedAccount<'info>,

    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}

pub fn process(ctx: Context<Migrate>) -> Result<()> {
    require!(
        ctx.accounts.global.initialized,
        CurveLaunchpadError::NotInitialized
    );

    // The curve must have sold out before it can migrate.
    require!(
        ctx.accounts.bonding_curve.complete,
        CurveLaunchpadError::BondingCurveNotComplete,
    );

    // Refresh source balances in case anything else mutated them earlier in
    // the same tx.
    ctx.accounts.bonding_curve_quote_account.reload()?;
    ctx.accounts.bonding_curve_token_account.reload()?;

    let lst_balance: u64 = ctx.accounts.bonding_curve_quote_account.amount;
    let meme_balance: u64 = ctx.accounts.bonding_curve_token_account.amount;

    // Raydium CPMM requires token_1_mint > token_0_mint (raw byte
    // comparison on the pubkeys). We pick which mint goes in which slot
    // at runtime so the caller doesn't need to grind a vanity MEME key.
    let lst_key = ctx.accounts.quote_mint.key();
    let meme_key = ctx.accounts.mint.key();
    let lst_is_token_0 = lst_key < meme_key;

    let (token_0_mint, token_1_mint) = if lst_is_token_0 {
        (
            ctx.accounts.quote_mint.to_account_info(),
            ctx.accounts.mint.to_account_info(),
        )
    } else {
        (
            ctx.accounts.mint.to_account_info(),
            ctx.accounts.quote_mint.to_account_info(),
        )
    };

    let (creator_token_0, creator_token_1) = if lst_is_token_0 {
        (
            ctx.accounts.bonding_curve_quote_account.to_account_info(),
            ctx.accounts.bonding_curve_token_account.to_account_info(),
        )
    } else {
        (
            ctx.accounts.bonding_curve_token_account.to_account_info(),
            ctx.accounts.bonding_curve_quote_account.to_account_info(),
        )
    };

    let (token_0_program, token_1_program) = if lst_is_token_0 {
        (
            ctx.accounts.token_program_2022.to_account_info(),
            ctx.accounts.token_program.to_account_info(),
        )
    } else {
        (
            ctx.accounts.token_program.to_account_info(),
            ctx.accounts.token_program_2022.to_account_info(),
        )
    };

    let (init_amount_0, init_amount_1) = if lst_is_token_0 {
        (lst_balance, meme_balance)
    } else {
        (meme_balance, lst_balance)
    };

    // Bonding-curve PDA seeds so the source-ATA debits inside Raydium's
    // CPI authorize.
    let mint_key_bytes = meme_key;
    let bonding_curve_signer: &[&[&[u8]]] = &[&[
        BondingCurve::SEED_PREFIX,
        mint_key_bytes.as_ref(),
        &[ctx.bumps.bonding_curve],
    ]];

    // Typed CPI — anchor's `declare_program!` codegen handles the
    // discriminator, argument serialization, and account encoding. The IDL
    // pins the slot ordering; we just need to put the right account in each
    // slot per the runtime swap above.
    let cpi_accounts = raydium_cp_swap::cpi::accounts::Initialize {
        creator: ctx.accounts.creator.to_account_info(),
        amm_config: ctx.accounts.amm_config.to_account_info(),
        authority: ctx.accounts.authority.to_account_info(),
        pool_state: ctx.accounts.pool_state.to_account_info(),
        token_0_mint,
        token_1_mint,
        lp_mint: ctx.accounts.lp_mint.to_account_info(),
        creator_token_0,
        creator_token_1,
        creator_lp_token: ctx.accounts.program_lp_token.to_account_info(),
        token_0_vault: ctx.accounts.token_0_vault.to_account_info(),
        token_1_vault: ctx.accounts.token_1_vault.to_account_info(),
        create_pool_fee: ctx.accounts.create_pool_fee.to_account_info(),
        observation_state: ctx.accounts.observation_state.to_account_info(),
        token_program: ctx.accounts.token_program.to_account_info(),
        token_0_program,
        token_1_program,
        associated_token_program: ctx.accounts.associated_token_program.to_account_info(),
        system_program: ctx.accounts.system_program.to_account_info(),
        rent: ctx.accounts.rent.to_account_info(),
    };

    let cpi_ctx = CpiContext::new_with_signer(
        ctx.accounts.cp_swap_program.to_account_info(),
        cpi_accounts,
        bonding_curve_signer,
    );

    raydium_cp_swap::cpi::initialize(cpi_ctx, init_amount_0, init_amount_1, 0u64)?;

    // Read the LP balance that landed in our retained ATA so we can surface
    // it in the event. Raydium's `initialize` mints LP straight into
    // program_lp_token (we never burn it).
    ctx.accounts.program_lp_token.reload()?;
    let lp_received: u64 = ctx.accounts.program_lp_token.amount;

    emit!(MigrateEvent {
        mint: meme_key,
        bonding_curve: ctx.accounts.bonding_curve.key(),
        pool_state: ctx.accounts.pool_state.key(),
        lp_mint: ctx.accounts.lp_mint.key(),
        quote_deposited: lst_balance,
        meme_deposited: meme_balance,
        lp_received,
        timestamp: Clock::get()?.unix_timestamp,
    });

    Ok(())
}
